GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/info/
###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
  "content":"Post is bad",
  "important":true
}
###
DELETE http://localhost:3001/api/persons/2